blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import CategoryListView, CategoryDetailView, ProductDetailView, ContactsTemplateView, \
    ProductCreateView, ProductUpdateView, ProductDeleteView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('', CategoryListView.as_view(), name='category_list'),
    path('catalog/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('product_detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, RestorePassword, UserUpdate

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_reset_form/', RestorePassword.as_view(), name='password_reset_form'),
    path('profile/', UserUpdate.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='Телефон', blank=True, null=True,
                             help_text='Введите номер телефона')

    country = models.CharField(max_length=50, verbose_name='Страна', blank=True, null=True,
                               help_text='Откуда Вы?')

    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Аватар', blank=True, null=True)

    token = models.CharField(max_length=100, verbose_name='Token', blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from catalog.forms import StyleFormMixin
from users.models import User
from django import forms


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'country')

users/views.py
import secrets
import string
import random

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    template_name = 'users/register.html'
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}'
        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения вашей почты перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        messages.success(self.request, 'На вашу почту отправлено письмо с подтверждением.')
        return super().form_valid(form)


class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserProfileForm

    def get_object(self, queryset=None):
        return self.request.user


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    messages.success(request, 'Ваша почта подтверждена. Теперь вы можете войти.')
    return redirect(reverse('users:login'))


class RestorePassword(TemplateView):
    template_name = 'users/password_reset_form.html'

    def post(self, *args, **kwargs):
        email = self.request.POST.get('email')
        user = User.objects.filter(email=email).first()
        if user:
            password = ''.join(random.choices(string.ascii_uppercase + string.digits, k=12))
            user.set_password(password)
            user.save()
            send_mail(
                subject='Создание нового пароля',
                message=f'Ваш новый пароль: {password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
            messages.success(self.request, 'Новый пароль отправлен на вашу почту.')
            return redirect(reverse('users:login'))
        else:
            messages.error(self.request, 'Пользователь с таким адресом электронной почты не найден.')
            return redirect(reverse('users:password_reset_form'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            {% for message in messages %}
            {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {% endif %}
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>
                <a href="{% url 'users:password_reset_form' %}" type="submit" class="btn btn-outline-success">
                    Восстановить пароль
                </a>
            </div>
        </div>
    </form>
    <div class="col-12 mb-md-5">
        <a class="btn btn-outline-secondary" href="{% url 'catalog:category_list' %}" role="button">Назад</a>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Инструкция по восстановлению пароля отправлена на указанный email</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-md-8 offset-md-2">
    {% for message in messages %}
    {% if message.tags == 'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {% else %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {% endif %}
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    <h3>Восстановление пароля</h3>
    <form method="post">
        {% csrf_token %}
        <input type="email" name="email" class="form-control w-25" placeholder="Введите ваш email">
        <button class="btn btn-outline-secondary" type="submit" role="button">Отправить</button>
    </form>
</div>
    {% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                </button>
            </div>
        </div>
    </form>
    <div class="col-12 mb-5">
        <a class="btn btn-outline-secondary" href="{% url 'catalog:category_list' %}" role="button">Назад</a>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}